### ISSUE TITLE
Search, match and iterate

### ISSUE THREAD

**Issue by bvssvni** [advancedresearch/monotonic_solver#4]
One idea is to add a different mode of solving where you receive data using a pattern you want to find.

- Search using inference rules, check against a closure mapping from `T -> Option<U>`
- Chain queries together for multiple constraints (checks two `U`s for equality)
- User iterator pattern to receive data while searching

### Syntax

A more convenient API could be added in a future version.

Conjugation (logical AND)

```
query1 : T -> Option<U>
query2 : T -> Option<U>
query1.and(query2) : T -> Option<U>
```

Match against any other fact that might be related:

```
query1.that(|x, y| ...) : T -> Option<V>
```

**Comment by judyjulien37** [comment]
Hello somebody put me through here
